@WebApi_HostAddress = http://localhost:5051

GET {{WebApi_HostAddress}}/task/list-all-task/4969A039-C082-44AD-A9A4-0EFE2BBA3DE3/0/100
Accept: application/json

###

POST {{WebApi_HostAddress}}/task/create-task
Content-Type: application/json

{
    "id": "4969A039-C082-44AD-A9A4-0EFE2BBA3DE3",
    "title": "Hello",
    "description": "world"
}

###

DELETE {{WebApi_HostAddress}}/task/delete-task/4969A039-C082-44AD-A9A4-0EFE2BBA3DE3/2daaad34-b02a-4bbb-8fc9-3bda2336d072
Accept: application/json

###

PATCH {{WebApi_HostAddress}}/task/update-task/4969A039-C082-44AD-A9A4-0EFE2BBA3DE3/2daaad34-b02a-4bbb-8fc9-3bda2336d072
Content-Type: application/json

{
  "title": "สวัสดี",
  "description": "ชาวโลก"
}

###