// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20251204035211_Add TaskBoard Table")]
    partial class AddTaskBoardTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Domain.TaskManagement.TaskBoardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskBoards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3")
                        });
                });

            modelBuilder.Entity("Domain.TaskManagement.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b42132ed-c735-770c-ab7a-4b232e813039"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create an optimized schema for the new project database.",
                            Title = "Design Database Schema"
                        },
                        new
                        {
                            Id = new Guid("a3511444-682a-7631-ab76-692e94ebbc8f"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop secure login and registration functionality.",
                            Title = "Implement Authentication"
                        },
                        new
                        {
                            Id = new Guid("9d531d27-c06a-766e-8160-b8f178d5243f"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Configure automated build and deployment pipeline.",
                            Title = "Set Up CI/CD Pipeline"
                        },
                        new
                        {
                            Id = new Guid("d87fc77d-e061-7438-9994-def849e4654b"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write comprehensive documentation for all API endpoints.",
                            Title = "Create API Documentation"
                        },
                        new
                        {
                            Id = new Guid("aabe2a3a-bd9e-7517-8e57-e99e4c53d130"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build a responsive dashboard for user analytics.",
                            Title = "Develop User Dashboard"
                        },
                        new
                        {
                            Id = new Guid("ce6114fc-3dd4-7733-bab1-f3004eeb4230"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improve database query speed and efficiency.",
                            Title = "Optimize Query Performance"
                        },
                        new
                        {
                            Id = new Guid("23f98e28-9302-7a62-a21f-4aba8049c1f3"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add support for online payments using Stripe.",
                            Title = "Integrate Payment Gateway"
                        },
                        new
                        {
                            Id = new Guid("4ad6e63e-4b4f-767d-a968-fea879cf4f59"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set up user roles and permissions for the system.",
                            Title = "Implement Role-Based Access"
                        },
                        new
                        {
                            Id = new Guid("0ce75541-8f68-7c96-971d-b0c18e251b21"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ensure code reliability with unit test coverage.",
                            Title = "Write Unit Tests"
                        },
                        new
                        {
                            Id = new Guid("c2e1c864-e71d-7043-bca5-97fcc8ff70a7"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set up centralized logging for error tracking.",
                            Title = "Configure Logging"
                        },
                        new
                        {
                            Id = new Guid("03b31f58-aafe-7ac9-9c0e-2c50280dd5b8"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create a visually appealing landing page for marketing.",
                            Title = "Design Landing Page"
                        },
                        new
                        {
                            Id = new Guid("3e0f06d4-bf71-72d2-9946-21ac609d4dd1"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement email alerts for user activities.",
                            Title = "Set Up Email Notifications"
                        },
                        new
                        {
                            Id = new Guid("d03ffa08-1e13-703f-b610-945675990fc7"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design and implement the mobile application interface.",
                            Title = "Develop Mobile App UI"
                        },
                        new
                        {
                            Id = new Guid("0be2285a-01b9-7677-b235-0ea0bb63181d"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Plan and implement regular data backups.",
                            Title = "Create Backup Strategy"
                        },
                        new
                        {
                            Id = new Guid("b7d15550-d1a2-7f5c-9b18-47949ccf8a09"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add search functionality with filters.",
                            Title = "Implement Search Feature"
                        },
                        new
                        {
                            Id = new Guid("25335252-e71d-7322-994d-dbc32d249c8e"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Improve page load speed and responsiveness.",
                            Title = "Optimize Frontend Performance"
                        },
                        new
                        {
                            Id = new Guid("892aa205-a8a7-7d25-a9b8-fc91b3464523"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enhance security by adding HTTP headers.",
                            Title = "Configure Security Headers"
                        },
                        new
                        {
                            Id = new Guid("bb18fbc1-7f10-792e-ac73-0b54c277ea8c"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create reports for user and admin dashboards.",
                            Title = "Develop Reporting Module"
                        },
                        new
                        {
                            Id = new Guid("2dbc57a4-dcb8-7e38-bcfa-4e538bce29df"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perform load testing to ensure scalability.",
                            Title = "Set Up Load Testing"
                        },
                        new
                        {
                            Id = new Guid("c3ef5dce-258e-7823-8dbe-722f0a0f1ad7"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allow users to upload files securely.",
                            Title = "Implement File Upload"
                        },
                        new
                        {
                            Id = new Guid("6bee3332-75d8-72c2-aafc-70ed06a8c33a"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design a smooth onboarding experience for new users.",
                            Title = "Create Onboarding Flow"
                        },
                        new
                        {
                            Id = new Guid("3fe0ab1c-9ac1-788a-aef3-f10270887a71"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enable login via Google and Facebook.",
                            Title = "Integrate Social Login"
                        },
                        new
                        {
                            Id = new Guid("43b7e292-3584-7823-97e3-27caa21a4a6c"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement real-time notifications for user actions.",
                            Title = "Develop Notification System"
                        },
                        new
                        {
                            Id = new Guid("a0a57651-e11a-7834-a151-b86163fc1946"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Configure tools to monitor and report errors.",
                            Title = "Set Up Error Monitoring"
                        },
                        new
                        {
                            Id = new Guid("2ac037d8-ccff-7b2e-b9c4-f1c5c07aeccf"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allow users to export data in CSV format.",
                            Title = "Implement Data Export"
                        },
                        new
                        {
                            Id = new Guid("798d42c3-a760-780a-8173-686631e49843"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop an admin interface for managing users.",
                            Title = "Create Admin Panel"
                        },
                        new
                        {
                            Id = new Guid("f4e1c6b1-212e-7ca5-a132-4473c111d54c"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enable localization for multiple languages.",
                            Title = "Add Multi-Language Support"
                        },
                        new
                        {
                            Id = new Guid("0536a50b-ce48-7563-95ab-8336e5c02382"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Secure the application with HTTPS.",
                            Title = "Configure SSL Certificates"
                        },
                        new
                        {
                            Id = new Guid("6935ab0d-a9e5-70d9-8c27-0b475fda2568"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add real-time chat functionality for users.",
                            Title = "Develop Chat Feature"
                        },
                        new
                        {
                            Id = new Guid("48cfb48f-89f8-702f-bb89-ba8344474646"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide a dark theme option for the UI.",
                            Title = "Implement Dark Mode"
                        },
                        new
                        {
                            Id = new Guid("66297792-78b4-7f85-aa9b-9e7995827864"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Integrate Google Analytics for tracking user behavior.",
                            Title = "Set Up Analytics"
                        },
                        new
                        {
                            Id = new Guid("f61cbacc-0781-7fe4-a8d2-755e3d3f2e2e"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add a help and FAQ section for users.",
                            Title = "Create FAQ Section"
                        },
                        new
                        {
                            Id = new Guid("2f6f5bb9-ff1f-7c0b-b48f-9cf3c6db158d"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement recurring billing for premium users.",
                            Title = "Develop Subscription System"
                        },
                        new
                        {
                            Id = new Guid("58d64f63-5a5a-7ade-abab-8ef8eed4553f"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Use lazy loading for images to improve performance.",
                            Title = "Optimize Image Loading"
                        },
                        new
                        {
                            Id = new Guid("542efcde-456a-7d7e-8fd0-e33dda521b1d"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add extra security for user accounts.",
                            Title = "Implement Two-Factor Authentication"
                        },
                        new
                        {
                            Id = new Guid("c9cc94f7-07ae-7270-b735-c232b106a62a"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prevent abuse by limiting API requests.",
                            Title = "Create API Rate Limiting"
                        },
                        new
                        {
                            Id = new Guid("88383c1a-c7b8-7965-8005-50eba4bad29f"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allow users to submit feedback easily.",
                            Title = "Develop Feedback Form"
                        },
                        new
                        {
                            Id = new Guid("6facf3b9-8a1f-7c19-86c1-fc331b3dd9b0"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enable push notifications for mobile users.",
                            Title = "Set Up Push Notifications"
                        },
                        new
                        {
                            Id = new Guid("59ec754f-ae62-73b7-8046-0fee8bddbf03"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ensure data integrity with proper validation.",
                            Title = "Implement Data Validation"
                        },
                        new
                        {
                            Id = new Guid("605e0ea5-41bc-72e5-820b-e32b45986db2"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Generate a sitemap for SEO optimization.",
                            Title = "Create Sitemap"
                        },
                        new
                        {
                            Id = new Guid("3a539c4a-e5d7-75b8-a4a2-e4aaf08473fb"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compress uploaded files to save storage.",
                            Title = "Develop File Compression"
                        },
                        new
                        {
                            Id = new Guid("0fdaa886-4ee5-7d53-af70-cdfe5891247f"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Track changes in user roles and permissions.",
                            Title = "Set Up Role Auditing"
                        },
                        new
                        {
                            Id = new Guid("be2f849e-cfcc-7ebd-96f0-5c473813af0e"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automatically save user progress in forms.",
                            Title = "Implement Auto-Save Feature"
                        },
                        new
                        {
                            Id = new Guid("b2162483-224d-7404-be52-e0d9d83635c4"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support multiple versions of the API.",
                            Title = "Create API Versioning"
                        },
                        new
                        {
                            Id = new Guid("30712589-3cff-75a3-a667-ece13f7f7591"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add basic image editing tools for users.",
                            Title = "Develop Image Editor"
                        },
                        new
                        {
                            Id = new Guid("fbb8b432-ee91-7d9b-920b-0014b236a164"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ensure high availability with replication.",
                            Title = "Set Up Database Replication"
                        },
                        new
                        {
                            Id = new Guid("569bd1f4-c4e0-71c2-a17c-d0e535e0bc3d"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allow users to reset their passwords securely.",
                            Title = "Implement Password Reset"
                        },
                        new
                        {
                            Id = new Guid("770021b9-88ff-7319-8fea-927cccc31077"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design user-friendly error pages.",
                            Title = "Create Custom Error Pages"
                        },
                        new
                        {
                            Id = new Guid("8c96900b-484d-7527-846d-74b522dbcf67"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enable tagging for better content organization.",
                            Title = "Develop Tagging System"
                        },
                        new
                        {
                            Id = new Guid("80130472-2a00-7f46-98ae-4641f7e25fc7"),
                            BoardId = new Guid("4969a039-c082-44ad-a9a4-0efe2bba3de3"),
                            CreatedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage and secure API traffic efficiently.",
                            Title = "Set Up API Gateway"
                        });
                });

            modelBuilder.Entity("Domain.TaskManagement.TaskEntity", b =>
                {
                    b.HasOne("Domain.TaskManagement.TaskBoardEntity", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Domain.TaskManagement.TaskBoardEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
